### ISSUE TITLE
'unexpected posit config’ error with bitlength choices other than N = 6,8,10 and 16

### ISSUE THREAD

**Issue by vinaysaxena93** [minhhn2910/QPyTorch#2]
(using qtorch 0.2.0 with Pytorch 1.8.0+Cuda 11.1)
All arbitrary posit configurations are not working as of now. Getting 'unexpected posit config’ error for the following configurations:
N = 7,9,11,12,13,14 and 15 with both es = 1 and 2

**Comment by minhhn2910** [comment]
it should be working now.
